version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Entrando no diretório do projeto..."
      - cd /var/www/html/oficina27
      - echo "Instalando dependências do backend..."
      - cd backend
      - npm install --production
      - cd ..
  build:
    commands:
      - echo "Copiando arquivos do frontend para o Apache..."
      - cp -r frontend/* /var/www/html/oficina27/frontend/
      - echo "Copiando arquivos do backend..."
      - cp -r backend/* /var/www/html/oficina27/backend/
      - echo "Build finalizado com sucesso."
artifacts:
  files:
    - "**/*"
